spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/smgt?createDatabaseIfNotExist=true
    username: neha
    password: neha
    driver-class-name: com.mysql.cj.jdbc.Driver